#!/bin/sh

echo "Remove Template Git Repo's git directory"
rm -rf .git

echo "Initialize npm project"
npm init -y

echo "Initialize yarn"
YARN=$(which yarn)
NPX=$(which npx)
if [ -z "$YARN" ]; then
    echo "yarn not exist"
    rm -f package.json
    exit 1
else
    $YARN
    $YARN add -D typescript ts-node @types/node prettier

    # TypeORM (with SQLite3 setup)
    if [ "$1" = "typeorm" ] || [ "$2" = "typeorm" ]; then
        echo "Initialize with TypeORM (sqlite3)"
        $YARN add reflect-metadata typeorm sqlite3
        mkdir -p ./src/entities
        touch ./src/entities/
        echo 'aW1wb3J0IHsKICBFbnRpdHksCiAgUHJpbWFyeUdlbmVyYXRlZENvbHVtbiwKICBDb2x1bW4sCiAgQ3JlYXRlRGF0ZUNvbHVtbiwKICBVcGRhdGVEYXRlQ29sdW1uLAp9IGZyb20gJ3R5cGVvcm0nOwoKQEVudGl0eSgpCmV4cG9ydCBjbGFzcyBVc2VyIHsKICBAUHJpbWFyeUdlbmVyYXRlZENvbHVtbih7IHR5cGU6ICdpbnRlZ2VyJyB9KQogIGlkOiBudW1iZXI7CgogIEBDb2x1bW4oeyB0eXBlOiAndGV4dCcgfSkKICBuYW1lOiBzdHJpbmc7CgogIEBDcmVhdGVEYXRlQ29sdW1uKCkKICBjcmVhdGVkQXQ6IERhdGU7CgogIEBVcGRhdGVEYXRlQ29sdW1uKCkKICB1cGRhdGVkQXQ6IERhdGU7Cn0K' | base64 -d > ./src/entities/User.ts
        echo 'ZXhwb3J0ICogZnJvbSAnLi9Vc2VyJzsK' | base64 -d > ./src/entities/index.ts
        echo 'aW1wb3J0IHsgRGF0YVNvdXJjZSB9IGZyb20gJ3R5cGVvcm0nOwppbXBvcnQgeyBVc2VyIH0gZnJvbSAnLi9lbnRpdGllcyc7CgpleHBvcnQgY29uc3QgU3FsaXRlRGF0YVNvdXJjZSA9IG5ldyBEYXRhU291cmNlKHsKICB0eXBlOiAnc3FsaXRlJywKICBkYXRhYmFzZTogJy4vdGVtcGxhdGUtZGF0YWJhc2UuZGInLAogIGVudGl0aWVzOiBbVXNlcl0sCiAgc3luY2hyb25pemU6IHRydWUsCiAgbG9nZ2luZzogdHJ1ZSwKICBzdWJzY3JpYmVyczogW10sCiAgbWlncmF0aW9uczogW10sCn0pOwo=' | base64 -d > ./src/data-source.ts
        echo 'aW1wb3J0IHsgU3FsaXRlRGF0YVNvdXJjZSB9IGZyb20gJy4vZGF0YS1zb3VyY2UnOwppbXBvcnQgeyBVc2VyIH0gZnJvbSAnLi9lbnRpdGllcyc7CgooYXN5bmMgKCkgPT4gewogIGF3YWl0IFNxbGl0ZURhdGFTb3VyY2UuaW5pdGlhbGl6ZSgpOwoKICBjb25zdCB1c2VyUmVwb3NpdG9yeSA9IFNxbGl0ZURhdGFTb3VyY2UuZ2V0UmVwb3NpdG9yeShVc2VyKTsKfSkoKTsK' | base64 -d >> ./src/index.ts
    fi

    # Jest
    if [ "$1" = "jest" ] || [ "$2" = "jest" ]; then
        echo "Initialize with Jest (ts-jest)"
        $YARN add -D jest @types/jest ts-jest
        $NPX ts-jest config:init
    fi

fi

echo "Initialize git repo"
git init

echo "Update readme"
echo "# $(basename $PWD)" > README.md

echo "Remove Init Template script"
exec rm -f ./init-template-local
