#!/bin/sh

echo "Remove Template Git Repo's git directory"
rm -rf .git

echo "Initialize npm project"
npm init -y

echo "Initialize yarn"
YARN=$(which yarn)
if [ -z "$YARN" ]; then
    echo "yarn not exist"
    rm -f package.json
    exit 1
else
    $YARN
    $YARN add -D typescript ts-node @types/node prettier
fi

echo "Initialize git repo"
git init

echo "Update readme"
echo "# $(basename $PWD)" > README.md

echo "Remove Init Template script"
exec rm -f ./init-template-local
